### PR TITLE
Don't fail early for --uninstall-devices

### PR DESCRIPTION
**Pull request by juergbi**
*Issue number of the reported bug or feature request: #12*

**Describe your changes**
This changes the behavior of `--uninstall-devices` to unlink as many device nodes as possible instead of giving up as soon as the first uninstall fails. It still exits with `ERR_EXIT_CODE` if at least one device node failed to uninstall.

**Testing performed**
I've tested it locally on Linux by manually removing some of the device nodes before running `userchroot --uninstall-devices`. I've also verified userchroot still works as expected with BuildStream and buildbox-run-userchroot (also on Linux).

### CODE REVIEW

**Review by edbaunton — DISMISSED** [review]

**Comment by jeremiahbonney** [comment]
Could this be pushed up again to make the CI check happy? It was added to this repo and requires commits to be signed off (git commit -s/--signoff).

**Review by jeremiahbonney — DISMISSED** [review]
LGTM! Thanks for the PR

**Comment by jeremiahbonney** [comment]
One last final thing, could this be rebased to pick up new changes? Apparently automatic rebasing of PRs isn't a thing on github :(

**Review by jeremiahbonney — APPROVED** [review]
LGTM...again!

**Pull request merged**
